### PR TITLE
Fix fs

### LINKED ISSUE #13: Add ability to update files and not just create them

### LINKED ISSUE #14: Make changes in the correct paths.
Right now it is relative in the same cli dir.

### PR DESCRIPTION
**Pull request by agamm**
Fixes https://github.com/alephmatic/nextjs-ai/issues/14 (Fix correct paths - relative)
Fixes https://github.com/alephmatic/nextjs-ai/issues/13 (Adds ability to update existing files)

### CODE REVIEW

File: aleph0/prompts.ts [hunk 1]
```diff
@@ -82,3 +81,39 @@ ${specificKnowledge}
 Changed snippet code:
 `;
 };
+
+export const updateFilePrompt = async (options: {
```
Comment (elie222) [inline aleph0/prompts.ts:85]: Do we want to remove copy and paste here? So when we improve the prompt we improve both together.

File: aleph0/prompts.ts [hunk 2]
```diff
@@ -1,7 +1,7 @@
 import { Snippet } from "./types";
 import { getSnippetFiles } from "./utils";
 
-export const findRelevantSnippet = (options: {
+export const findRelevantSnippetPrompt = (options: {
```
Comment (elie222) [inline aleph0/prompts.ts:4]: Good suffix. Was confusing me before.

File: aleph0/index.ts [hunk 3]
```diff
@@ -64,19 +68,43 @@ async function generate(userText: string) {
...
   consola.info(
-    `Step 3 - for each file in the changes array, ask GPT 4 for the new file and create/modify it.`
+    `\nStep 3 - for each file in the changes array, ask GPT 4 for the new file and create/modify it.`
   );
   for (const change of changes) {
-    consola.log(`Change: ${JSON.stringify(change, null, 2)}`);
+    consola.log(`Change operation: ${JSON.stringify(change, null, 2)}`);
+
+    const sourceFilePath = path.join(RELATIVE_DIR, change.sourcePath);
+    const sourceFile = Bun.file(sourceFilePath);
```
Comment (elie222) [inline aleph0/index.ts:79]: Maybe we drop bun usage. No major benefit to us atm. And in other places we've been using fs anyway. Bun read/write is an alternative to fs.

File: aleph0/index.ts [hunk 4]
```diff
@@ -64,19 +68,43 @@ async function generate(userText: string) {
...
+    let fileContents;
+    if (await sourceFile.exists()) {
+      consola.info("Updating existing file");
+      const currentFileContents = await sourceFile.text();
+      fileContents = await ai(
+        await updateFilePrompt({
+          snippet,
+          userText,
+          specificKnowledge,
+          fileContents: currentFileContents,
```
Comment (elie222) [inline aleph0/index.ts:91]: At some point we'll have to handle going over max tokens. But I think we're okay now with 8k limit. Which I believe is around 6k words.

**Review by elie222 — CHANGES_REQUESTED** [review]
No major issues. Happy to see the code getting cleaner and more understandable.

**Comment by elie222** [comment]
See file.ts for our file system related commands btw.
